//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.LoginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginServiceReference.ILoginManagement")]
    public interface ILoginManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginManagement/add", ReplyAction="http://tempuri.org/ILoginManagement/addResponse")]
        void add();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginManagement/add", ReplyAction="http://tempuri.org/ILoginManagement/addResponse")]
        System.Threading.Tasks.Task addAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginManagementChannel : WebUI.LoginServiceReference.ILoginManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginManagementClient : System.ServiceModel.ClientBase<WebUI.LoginServiceReference.ILoginManagement>, WebUI.LoginServiceReference.ILoginManagement {
        
        public LoginManagementClient() {
        }
        
        public LoginManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void add() {
            base.Channel.add();
        }
        
        public System.Threading.Tasks.Task addAsync() {
            return base.Channel.addAsync();
        }
    }
}
