//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int Course_Id { get; set; }
        public string Name { get; set; }
        public int Professor_Professor_Id { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
