//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginManagement
{
    using Dal;
    using System;
    using System.Collections.Generic;

    public partial class Users : IEntity
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public Nullable<int> Year { get; set; }
        public string Type { get; set; }
        public int RegNumber { get; set; }
        public Nullable<int> Section { get; set; }
        public int Profile { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Profiles Profiles { get; set; }
        public virtual Sections Sections { get; set; }

        public int GetId()
        {
            return this.Id;
        }
    }
}
