//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
namespace LoginManagement
{
    using Dal;
    using System;
    using System.Collections.Generic;

    [DataContract]
   public partial class User : IEntity {
        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public string FirstName { get; set; }

        [DataMember]
        public string LastName { get; set; }

        [DataMember]
        public string Password { get; set; }

        [DataMember]
        public string Email { get; set; }

        [DataMember]
        public string Login { get; set; }

        [DataMember]
        public Nullable<int> Year { get; set; }

        [DataMember]
        public string Type { get; set; }

        [DataMember]
        public Nullable<int> RegNumber { get; set; }

        [DataMember]
        public Nullable<int> Section { get; set; }

        [DataMember]
        public int Profile { get; set; }

        [DataMember]
        public virtual Profile Profile1 { get; set; }

        [DataMember]
        public virtual Section Section1 { get; set; }

        public int GetId()
        {
            return this.Id;
        }

        public User(int regNumber, string lastName, string firstName, Nullable<int> year, Nullable<int> section, string email, string type, string login, string password ) {
            RegNumber = regNumber;
            LastName = lastName;
            FirstName = firstName;
            Year = year;
            Section = section;
            Email = email;
            Type = Type;
            Login = login;
            Password = password;
        }

    }
}
